openapi: 3.0.3
info:
  title: Traveler Bloggers Platform API
  description: API documentation for the Traveler Bloggers Platform
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /users/register:
    post:
      summary: Register a new user
      description: Registers a new user in the system using either email/password, Google OAuth, or Facebook OAuth. The user must provide either a password, a Google token, or a Facebook token, but not more than one.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - username
                - email
              properties:
                first_name:
                  type: string
                  maxLength: 50
                  example: Hema
                  description: The user's first name
                last_name:
                  type: string
                  maxLength: 50
                  example: Atar
                  description: The user's last name
                username:
                  type: string
                  maxLength: 50
                  example: hemaatar
                  description: The user's unique username
                email:
                  type: string
                  format: email
                  maxLength: 100
                  example: hemaatar636@gmail.com
                  description: The user's email address (must be unique)
                password:
                  type: string
                  example: Password123
                  description: The user's password (required if google_token and facebook_token are not provided)
                google_token:
                  type: string
                  example: eyJhbGciOiJSUzI1NiIsImtpZCI6IjgyMWYzYmM2...
                  description: Google OAuth ID token (required if password and facebook_token are not provided)
                facebook_token:
                  type: string
                  example: EAAH2jZ...
                  description: Facebook OAuth access token (required if password and google_token are not provided)
              oneOf:
                - required: [password]
                - required: [google_token]
                - required: [facebook_token]
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: b3633c92-8528-4693-b652-c55c9ef6fd16
                      first_name:
                        type: string
                        example: Hema
                      last_name:
                        type: string
                        example: Atar
                      username:
                        type: string
                        example: hemaatar
                      email:
                        type: string
                        example: hemaatar636@gmail.com
                      role:
                        type: string
                        example: general_user
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    description: JWT token for authentication
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "\"password\" must be provided or \"google_token\" must be provided or \"facebook_token\" must be provided"
        '409':
          description: Conflict (email or username already exists)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email already exists
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server error
                  error:
                    type: string
                    example: Facebook token email mismatch

  /users/login:
    post:
      summary: Log in a user
      description: Logs in a user using either email/password, Google OAuth, or Facebook OAuth. The user must provide either a password, a Google token, or a Facebook token, but not more than one.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 100
                  example: hemaatar636@gmail.com
                  description: The user's email address
                password:
                  type: string
                  example: Password123
                  description: The user's password (required if google_token and facebook_token are not provided)
                google_token:
                  type: string
                  example: eyJhbGciOiJSUzI1NiIsImtpZCI6IjgyMWYzYmM2...
                  description: Google OAuth ID token (required if password and facebook_token are not provided)
                facebook_token:
                  type: string
                  example: EAAH2jZ...
                  description: Facebook OAuth access token (required if password and google_token are not provided)
              oneOf:
                - required: [password]
                - required: [google_token]
                - required: [facebook_token]
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: b3633c92-8528-4693-b652-c55c9ef6fd16
                      first_name:
                        type: string
                        example: Hema
                      last_name:
                        type: string
                        example: Atar
                      username:
                        type: string
                        example: hemaatar
                      email:
                        type: string
                        example: hemaatar636@gmail.com
                      role:
                        type: string
                        example: general_user
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    description: JWT token for authentication
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "\"password\" must be provided or \"google_token\" must be provided or \"facebook_token\" must be provided"
        '401':
          description: Unauthorized (invalid credentials)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server error
                  error:
                    type: string
                    example: Facebook token email mismatch
